### ISSUE TITLE
補完が自動的に始まりません

### ISSUE THREAD

**Issue by delphinus** [rinx/cmp-skkeleton#2]
最新の nvim-cmp & cmp-skkeleton だと補完が自動的に始まらないようです。以下の autocmd で解消したのですが、これって正常な動作でしょうか？

```vim
augroup cmp_skkeleton
  autocmd!
  autocmd User skkeleton-handled call v:lua.require'cmp'.complete()
augroup END
```

**Comment by rinx** [comment]
@delphinus 報告ありがとうございます。
補完をトリガーする keyword patterns が間違っていたようなので、以下の commit で修正しました。
f03f301

提案いただいた autocmd での対応でもよさそうですが、本来想定していたのは keyword patterns での補完の開始です。

**Comment by delphinus** [comment]
確認しました。ありがとうございます。確かにこちらの方が堅実ですね。
